### Lists

Ordered collections of data, immutable. Insertion and deletion is costly. 

In [3]:
list = [1,2, 'hello', 4]
print(list)

# multi-dimensional list
list2 = [['hello', 'world'], ['yo']]

#accessing an element using index numbers
print(list[1]) # second element
print(list[-1]) # last element
print(list2[0][1]) # first row, second column

[1, 2, 'hello', 4]
2
4
world


### Tuples

Similar to lists but immutable.

In [5]:
Tuple = ("Ali", "Huss")
print(Tuple)

#casting list as tuple
list = [1,2,3,4,5]
Tuple = tuple(list)

#accessing element using indexing
print(Tuple[0]) #first element
print(Tuple[-2]) #second last element

('Ali', 'Huss')
1
4


### Sets

Mutable collection of data with no dupes.

In [6]:
Set = set([1,2,4,3,4])
print(Set)

{1, 2, 3, 4}


### Frozen Sets

Immutable objects that only support methods and operatores that produce aresult without affecting the set itself.

In [9]:
frozen_set =frozenset(['e', 'f', 'g'])
print(frozen_set)

#frozen_set.add("h") 

# will result in error

frozenset({'e', 'f', 'g'})


### Strings

Immutable array of bytes. Modifying strings will result in creating new copies.

In [10]:
string = "Ali Hussain"
print(string)
print(string[0]) #first element
print(string[-1]) #last element

Ali Hussain
A
n


### Dictionary

Unordered collection of data that stores data in the format of key:value pair. Of any hashable type i.e. strings, tuples

In [12]:
Dict = {'Name': 'Ali Hussain', 1: [1,2,3,4]}
print(Dict)

#accessing element using key
print(Dict['Name'])

#accessing element using get() method
print(Dict.get(1))

#dictionary using dictionary comprehension
myDict = {x:x**2 for x in [1,2,3,4,5]}
print(myDict)

{'Name': 'Ali Hussain', 1: [1, 2, 3, 4]}
Ali Hussain
[1, 2, 3, 4]
{1: 1, 2: 4, 3: 9, 4: 16, 5: 25}


### Matrix 


In [9]:
import numpy as np
a = np.array([[1,2,3,4],[4,5,5,1],[8,3,20,1], [1,2,3,5]])
print(a)

[[ 1  2  3  4]
 [ 4  5  5  1]
 [ 8  3 20  1]
 [ 1  2  3  5]]
[[ 1  2  3  4  4  5  5  1]
 [ 8  3 20  1  1  2  3  5]]


In [ ]:
# Reshape from 4x4 to 2x8
m = np.reshape(a,(2,8)) 
print(m)

In [ ]:
#accessing element
print(a[1]) # second row
print(a[2][0]) #third row, first column

In [14]:
#adding element
m = np.append(a, [[1,15,13,11]], 0)
print(m)

[[ 1  2  3  4]
 [ 4  5  5  1]
 [ 8  3 20  1]
 [ 1  2  3  5]
 [ 1 15 13 11]]


In [15]:
#deleting element
m = np.delete(m, [1], 0) # delete second row
print(m)

[[ 1  2  3  4]
 [ 8  3 20  1]
 [ 1  2  3  5]
 [ 1 15 13 11]]


### bytearray

gives a mutable sequence of integers in range [0,256)

In [20]:
a = bytearray((12,8,25,2))
print(a)

#accessing elements
print(a[1]) #2nd element

#modifying elements
a[1] = 3 #change 2nd element from 8 to 3
print(a)

#adding elements
a.append(30)
print(a)


bytearray(b'\x0c\x08\x19\x02')
8
bytearray(b'\x0c\x03\x19\x02')
bytearray(b'\x0c\x03\x19\x02\x1e')
